print(" ")
print("welcome to my fill in the blanks story")
input()
print("add words to create a story")
input()
number1 = input("first add a number:")
pnoun1 = input("next, a plural noun:")
verb1 = input("verb:")
adj1 = input("adjective:")
number2 = input("number:")
place = input("place:")
name1 = input("name:")
name2 = input("another name:")
verbed1= input("verb in past tense:")
noun1 = input("noun:")
verbed2 = input("verb in past tense:")
number3 = input("number:")
adj2 = input("adjective:")
adj3 = input("Another adjective:")
verbed3 = input("Verb in past tense:")
verbed4 = input("another verb in past tense:")
noun2 = input("noun:")
verbed5 = input("verb in past tense:")
pnoun2 = input("plural noun:")
verb2 = input("verb:")
adverb = input("adverb:")
number4 = input("and finally a number:")

input("here is your story?")

print("_____________________________________________")

print(f"On july {number1} 1969, 2 american {pnoun1} were the first to {verb1} on the moon. This trip took {number2} days to reach the moon from {place}. {name1} Armstrong and {name2} aldrin {verbed1} onto the {noun1} of the moon, armstrong {verbed2} the famous words, thats {number3} {adj2} steps for man, 1 {adj3} leap for mankind. soon after, Aldrin {verbed3} onto the moon and together, they {verbed4} a US {noun2} on the surface. they {verbed5} {pnoun2} from the moons surface to {verb2} back to earth and {adverb} returned home {number4} days later.")

print("_____________________________________________")

print("thank you for playing")